### ISSUE TITLE
Embulk doesn't remove temporary files when job fails

### ISSUE THREAD

**Issue by chie8842** [llibra/embulk-output-s3#13]
When I ran embulk job to output files to s3 which is too big so I had IOException Error and Embulk job was failed.
After job failed, I recognized that temporary files at /tmp wasn't removed.
I think we should implement exception handler to remove temporary files.

**Comment by chie8842** [comment]
Oh, I'm sorry. I created pull request. 
I didn't recognize that you have assigned yourself.
You can abort if you don't like it.
Thank you!

**Comment by llibra** [comment]
np. thank you for your PR.

**Comment by llibra** [comment]
Merged. c1cab1506c7dbf24cc86af03a9d60bf031fc97bf.

Sorry for the late response.
