### ISSUE TITLE
file_ext

### ISSUE THREAD

**Issue by E-Tanamachi** [llibra/embulk-output-s3#39]
If you set "file_ext" to ".csv", the output file name will be

_.000.00.csv

As a result, an extra "." is entered before "000".

On the other hand, if you set "file_ext" to "csv", the output file name will be

_000.00csv

and the extension is no longer ".csv".

**Comment by hiroyuki-sato** [comment]
Hello, @E-Tanamachi 

The default file format is `<path_prefix><sequence_format><file_ext>`. 
If you set the file_ext as `.csv`, It will be `<path_prefix><sequence_format>.csv`
The `<sequence_format>` format is `.%03d.%02d` by default.
The first part(`%03d`) is the task index, and the second part(`%02d`) is the sequence number in a task.
Those will replace with specific numbers.

The `file_ext` doesn't contain `.` unlike [`embulk-output-s3`](https://www.embulk.org/docs/built-in.html#file-output-plugin). It is a historical reason. So You need to set `.` explicitly.

**Comment by E-Tanamachi** [comment]
Thank you, Hiroyuki.

I'm also using embulk-output-azure_blob_storage,
With the setting "file_ext: csv",

_000.00.csv

I'm wondering because the file name is .

> Hello, @E-Tanamachi
> 
> The default file format is `<path_prefix><sequence_format><file_ext>`. If you set the file_ext as `.csv`, It will be `<path_prefix><sequence_format>.csv` The `<sequence_format>` format is `.%03d.%02d` by default. The first part(`%03d`) is the task index, and the second part(`%02d`) is the sequence number in a task. Those will replace with specific numbers.
> 
> The `file_ext` doesn't contain `.` unlike [`embulk-output-s3`](https://www.embulk.org/docs/built-in.html#file-output-plugin). It is a historical reason. So You need to set `.` explicitly.

**Comment by E-Tanamachi** [comment]
thank you very much.
With the following settings,
```
   file_ext: .csv
   sequence_format: "%03d.%02d"
```
Both s3 and azure storage gave the same result.

**Comment by hiroyuki-sato** [comment]
Cloud you close this issue when you resolve it?
