### ISSUE TITLE
Pull AWS credentials from profile file

### ISSUE THREAD

**Issue by strife25** [llibra/embulk-output-s3#9]
It would be nice to have AWS authentication fall back to use local profile files if environment variables are not set. This would primarily help with local testing.

**Comment by strife25** [comment]
I am actually thinking this is some sort of bug now - trying to run this plugin on an EC2 instance with IAM is resulting in the following error:

`Error: com.amazonaws.AmazonClientException: Unable to load AWS credentials from environment variables (AWS_ACCESS_KEY_ID (or AWS_ACCESS_KEY) and AWS_SECRET_KEY (or AWS_SECRET_ACCESS_KEY))`

**Comment by llibra** [comment]
I fixed this in 265250a and released version 1.3.0.
Could you test 1.3.0 on your environment?
